spring:
  datasource:
    url: abc
    username: abc
    password: abc
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: abc
            client-secret: abc
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
#  liquibase:
#    change-log: classpath:/liquibase/changesets/db.changelog.yaml
#    enabled: true
#    default-schema: challenge_arena
security:
  jwt:
    secret: abc
    access: 3600000
    refresh: 2592000000
logging:
  level:
    org.springframework.web: DEBUG